openapi: "3.0.1"
info:
  title: "http-crud-gustavo-api"
  version: "2024-03-10 20:55:13UTC"
servers:
- url: "https://31p9r2n8nl.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /items/{id}:
    get:
      responses:
        default:
          description: "Default response for GET /items/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:339713117127:function:http-crud-gustavo-function/invocations"
        connectionType: "INTERNET"
    put:
      responses:
        default:
          description: "Default response for PUT /items/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:339713117127:function:http-crud-gustavo-function/invocations"
        connectionType: "INTERNET"
    delete:
      responses:
        default:
          description: "Default response for DELETE /items/{id}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:339713117127:function:http-crud-gustavo-function/invocations"
        connectionType: "INTERNET"
    parameters:
    - name: "id"
      in: "path"
      description: "Generated path parameter for id"
      required: true
      schema:
        type: "string"
  /items:
    get:
      responses:
        default:
          description: "Default response for GET /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:339713117127:function:http-crud-gustavo-function/invocations"
        connectionType: "INTERNET"
    post:
      responses:
        default:
          description: "Default response for POST /items"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:339713117127:function:http-crud-gustavo-function/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
